version: '3.8'

services:
  web:
    build: .
    command: python -u run.py
    ports:
      - "5000:5000"
    volumes:
      - .:/app

    # ðŸ‘‡ ADD THIS LINE HERE
    env_file:
      - .env

    environment:
      - DATABASE_URL=postgresql://hello_hostel:secure_pass@db:5432/hostel_db
      - FLASK_APP=app
      - FLASK_DEBUG=1
      - OAUTHLIB_INSECURE_TRANSPORT=1
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}

    depends_on:
      - db

  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=hello_hostel
      - POSTGRES_PASSWORD=secure_pass
      - POSTGRES_DB=hostel_db

volumes:
  postgres_data:
